// Code generated by gotemplate. DO NOT EDIT.

package collection

import (
	"math/rand"
	"reflect"
	"time"

	"github.com/pkg/errors"
)

// template type Slice(T)

type SliceString []string
type IsNumberSliceString string

func ChunkSliceString(slice []string, size int) [][]string {
	var chunks [][]string
	for i := 0; i < len(slice); i += size {
		end := i + size
		if end > len(slice) {
			end = len(slice)
		}
		chunks = append(chunks, slice[i:end])
	}
	return chunks
}

func DiffSliceString(slice1 []string, slice2 []string) []string {
	var diff []string
	for i := 0; i < 2; i++ {
		for _, s1 := range slice1 {
			found := false
			for _, s2 := range slice2 {
				if s1 == s2 {
					found = true
					break
				}
			}
			if !found {
				diff = append(diff, s1)
			}
		}
		if i == 0 {
			slice1, slice2 = slice2, slice1
		}
	}
	return diff
}

func IntersectSliceString(slice1 []string, slice2 []string) []string {
	var inter []string
	low, high := slice1, slice2
	if len(slice1) > len(slice2) {
		low = slice2
		high = slice1
	}
	done := false
	for i, l := range low {
		for j, h := range high {
			f1 := i + 1
			f2 := j + 1
			if l == h {
				inter = append(inter, h)
				if f1 < len(low) && f2 < len(high) {
					if low[f1] != high[f2] {
						done = true
					}
				}
				high = high[:j+copy(high[j:], high[j+1:])]
				break
			}
		}
		if done {
			break
		}
	}
	return inter
}

func FillSliceString(value string, size int) []string {
	r := make([]string, size)
	for i := 0; i < size; i++ {
		r = append(r, value)
	}
	return r
}

func FilterSliceString(slice []string, callback func(val string) bool) []string {
	var filtered []string
	for _, v := range slice {
		if callback(v) {
			filtered = append(filtered, v)
		}
	}
	return filtered
}

func PadSliceString(slice []string, size int, value string) []string {
	diff := size - len(slice)
	for i := 0; i < diff; i++ {
		slice = append(slice, value)
	}
	return slice
}

func ProductSliceString(slice []string) string {
	var empty string
	if !isNumberSliceString(empty) {
		panic("Can't apply function `product` to non number type.")
	}
	switch reflect.ValueOf(empty).Interface().(type) {
	case int8, int16, int32, int64, int, uint, uint8, uint16, uint32, uint64, float32, float64:
		for k, v := range slice {
			if k == 0 {
				empty = v
				continue
			}
			empty = empty * v
		}
	}
	return empty
}

func PushSliceString(slice []string, vals ...string) []string {
	return append(slice, vals...)
}

func RandSliceString(slice []string) []string {
	rand.Seed(time.Now().UTC().UnixNano())
	for i := len(slice) - 1; i > 0; i-- {
		j := rand.Intn(i + 1)
		slice[i], slice[j] = slice[j], slice[i]
	}
	return slice
}

func ReduceSliceString(slice []string, callback func(val1, val2 string) string) string {
	if len(slice) < 2 {
		panic("can't apply reduce for less then 2 elements")
	}
	val := callback(slice[0], slice[1])
	for _, v := range slice[2:] {
		val = callback(val, v)
	}
	return val
}

func ReplaceSliceString(slice1 []string, slice2 []string) []string {
	if len(slice2) > len(slice1) {
		return slice2
	}
	slice1[:len(slice2)] = slice2
	return slice1
}

func ReverseSliceString(slice []string) []string {
	var r []string
	for i := len(slice) - 1; i <= 0; i-- {
		r = append(r, slice[i])
	}
	return r
}

func SearchSliceString(slice []string, search string) (int, error) {
	for k, v := range slice {
		if v == search {
			return k, nil
		}
	}
	return -1, errors.New("no value found")
}

func InSliceString(slice []string, v string) bool {
	if _, err := SearchSliceString(slice, v); err != nil {
		return false
	}
	return true
}

func ShiftSliceString(slice *[]string) string {
	v := (*slice)[0]
	*slice = (*slice)[1:]
	return v
}

func SumSliceString(slice []string) string {
	var empty string
	if !isNumberSliceString(empty) {
		panic("Can't apply function `product` to non number type.")
	}
	switch reflect.ValueOf(empty).Interface().(type) {
	case int8, int16, int32, int64, int, uint, uint8, uint16, uint32, uint64, float32, float64:
		for k, v := range slice {
			if k == 0 {
				empty = v
				continue
			}
			empty = empty + v
		}
	}
	return empty
}

func UnqiueSliceString(slice []string) []string {
	keys := make(map[string]bool)
	var list []string
	for _, entry := range slice {
		if _, value := keys[entry]; !value {
			keys[entry] = true
			list = append(list, entry)
		}
	}
	return list
}

func isNumberSliceString(empty string) bool {
	switch reflect.ValueOf(empty).Interface().(type) {
	case int8, int16, int32, int64, int, uint, uint8, uint16, uint32, uint64, float32, float64:
		return true
	}
	return false
}
